spring:
  application:
    name: api-gatewaye

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/realm-projet-microservice
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8765

app:
  keycloak:
    admin:
      username: cherif
      password: passer
    issuerUri: http://localhost:8080/realms/realm-projet-microservice
    login:
      url: http://localhost:8080/realms/realm-projet-microservice/protocol/openid-connect/token
    server:
      url: http://localhost:8080
    client-secret: 5vi1tnncR2mtNKRXYpsgoOSsAl8ysdez
    realm:
      name: realm-projet-microservice
    client-id: projet-microservice-app
    grant-type: password
keycloak:
  use-resource-role-mappings: 'true'
  ssl-required: external


